name: Bug Report
description: File a bug report
title: "[Bug]"
labels: bug
body: 
  - type: textarea
    id: issue
    attributes:
      label: Description of the issue
      description: What's the issue you encountered?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: How can the issue be reproduced?
      placeholder: Describe each step as precisely as possible
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: Log file
      description: Reproduce the issue exactly in a new neovim session, then run the neovim command `:lua require("harpoon.logger"):show()`
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Neovim Version
      description: In your terminal, run `nvim --version`
      placeholder: "e.g. 0.9.4"
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: Minimal Config
      description: For ease of replication in the case of complex behaviour, paste a small config under which the bug occurs.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context?
      description: |
        - Additional info about your environment:
        - Any other information relevant to your issue.
    validations:
      required: false
